(ns fluxo.all-tests
  (:require [fluxo.models.add-token-test]
            [fluxo.models.amount-step-test]
            [fluxo.models.confirmation-step-test]
            [fluxo.models.create-stream-test]
            [fluxo.models.duration-step-test]
            [fluxo.models.onboarding-test]
            [fluxo.models.recipient-step-test]
            [fluxo.money-test]
            [fluxo.views.add-token-test]
            [fluxo.views.amount-step-test]
            [fluxo.views.confirmation-step-test]
            [fluxo.views.duration-step-test]
            [fluxo.views.onboarding-test]
            [fluxo.views.recipient-step-test]
            [fluxo.wallet-test]
            [fluxo.web3-test]))
