name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java JDK
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.1.java11'

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4

      - name: Compile
        run: lein shadow compile app karma-test

      - name: Test
        run: npx karma start --single-run

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: compiled-app
          path: resources/public

  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: compiled-app
          path: resources/public

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
